apiVersion: v1
kind: Service
metadata:
  name: shopservice-np-srv
spec:
  type: NodePort
  selector:
    app: shopservice
  ports:
    - name: shopservice
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shopservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: shopservice
  ports:
  - name: shopservice
    protocol: TCP
    port: 80
    targetPort: 80