apiVersion: v1
kind: Service
metadata:
  name: userregistrationservice-np-srv
spec:
  type: NodePort
  selector:
    app: userregistrationservice
  ports:
    - name: userregistrationservice
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: userregistrationservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: userregistrationservice
  ports:
  - name: userregistrationservice
    protocol: TCP
    port: 80
    targetPort: 80