apiVersion: apps/v1
kind: Deployment
metadata:
  name: userstorageservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userstorageservice
  template:
    metadata:
      labels:
        app: userstorageservice
    spec:
      containers:
        - name: userstorageservice
          image: mpiryutko/userstorageservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: userstorageservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: userstorageservice
  ports:
  - name: userstorageservice
    protocol: TCP
    port: 80
    targetPort: 80 
  - name: plafromgrpc
    protocol: TCP
    port: 666
    targetPort: 666