apiVersion: apps/v1
kind: Deployment
metadata:
  name: userreg-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userregistrationservice
  template:
    metadata:
      labels:
        app: userregistrationservice
    spec:
      containers:
        - name: userregistrationservice
          image: mpiryutko/userregistrationservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: userregistrationservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: userregistrationservice
  ports:
  - name: userregistrationservice
    protocol: TCP
    port: 80
    targetPort: 80